[package]
name = "bve-client"
version = "0.0.1"
description = "BVE-Reborn's main game client"
license = "MPL-2.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"
publish = false

repository = "https://gitlab.bvereborn.com/bve-reborn/bve-reborn"
readme = "README.md"
categories = ["games", "simulation"]
keywords = ["bve", "rex", "engine"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bve = { version = "0.0.1", path = "../bve" }
bve-render = { version = "0.0.1", path = "../bve-render" }
circular-queue = "0.2.4"
cgmath = "0.17.0"
env_logger = "0.7.1"
image = { version = "0.23.2", default-features = false, features = ["bmp", "gif", "png"] }
num-traits = "0.2.11"
itertools = "0.9"
futures = { version = "0.3.4", features = ["executor"] }
log = "0.4.8"
winit = "0.22.0"
