[package]
name = "bve-corpus"
version = "0.0.0-Placeholder"
description = "Program to run bve parsers against the entire corpus"
license = "MPL-2.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"

repository = "https://gitlab.bvereborn.com/bve-reborn/bve-reborn"
readme = "README.md"
categories = ["games", "parsing", "rendering::data-formats", "simulation"]
keywords = ["bve", "serialization", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
indicatif = "0.13.0"
itertools = "0.8.2"
libc = "0.2.66"
structopt = "0.3.8"
walkdir = "2.3.1"
winapi = { version =  "0.3.8", features = ["processthreadsapi"] }