[package]
name = "bve-render"
version = "0.0.1"
description = "BVE-Reborn's renderer and window managment"
license = "MPL-2.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"

repository = "https://github.com/BVE-Reborn/bve-reborn"
readme = "README.md"
categories = ["games", "rendering", "graphics"]
keywords = ["bve", "renderer", "wgpu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
async-std = "1.5.0"
bve = { version = "0.0.1", path = "../bve" }
dashmap = "3.11.1"
log = "0.4.8"
nalgebra-glm = "0.7.0"
num-traits = "0.2.11"
imgui = "0.4.0-pre"
imgui-wgpu = "0.6.0"
include_dir = "0.6.0"
indexmap = "1.3.2"
image = { version = "0.23.2", default-features = false }
itertools = "0.9"
once_cell = "1.3.1"
renderdoc = { version = "0.8.1", default-features = false, optional = true }
winit = "0.22.1"
wgpu = "0.5.0"
zerocopy = "0.3.0"
