cargo-features = ["named-profiles"]

[workspace]
members = ["bve*"]

[patch.crates-io]
imgui = { git = "https://github.com/jaynus/imgui-rs", rev = "fd3caf3e5b1141e8af3725f8c6898524c14426b0" }
imgui-wgpu = { git = "https://github.com/BVE-Reborn/imgui-wgpu-rs.git", rev = "bbaa701361680f22dededc2f21b467db47f4f968" }
imgui-winit-support = { git = "https://github.com/jaynus/imgui-rs.git", rev = "fd3caf3e5b1141e8af3725f8c6898524c14426b0" }
obj = { git = "https://github.com/kvark/obj.git", rev = "a1df2284ea11112aba5ee38b39b208344b634d7d" }
winit = { git = "https://github.com/Osspial/winit.git", rev = "78a62ec5473e9cd5472c18f859103b0b0cb88362" }

[profile.dev]
opt-level = 0

[profile.dev.package.pico-args]
opt-level = 0

[profile.opt-dev]
inherits = "dev"
opt-level = 3
incremental = true
overflow-checks = true
debug-assertions = true
debug = true

[profile.release]
debug = false
debug-assertions = false
lto = true

[profile.profile]
inherits = "release"
debug = true
debug-assertions = false
lto = true
