[workspace]
members = ["bve*"]
exclude = ["bve-reborn"]    # Ignore the Unity project cause it's not a Rust project

[patch.crates-io]
cgmath = { git = "https://github.com/rustgd/cgmath.git", rev = "50a345b7c439c492a9c658dbb432f6cbd70a0557" }
crossbeam = { git = "https://github.com/crossbeam-rs/crossbeam.git", rev = "ebecb82c740a1b3d9d10f235387848f7e3fa9c68" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing.git", rev = "1c3bb7087db7570e91d27cd40e5e27f0f9a2c8b1" }

[profile.release]
overflow-checks = true
debug-assertions = true
debug = true
