cargo-features = ["named-profiles"]

[workspace]
members = ["bve*"]

[patch.crates-io]
cgmath = { git = "https://github.com/rustgd/cgmath.git", rev = "50a345b7c439c492a9c658dbb432f6cbd70a0557" }
obj = { git = "https://github.com/kvark/obj.git", rev = "a1df2284ea11112aba5ee38b39b208344b634d7d" }
winit = { git = "https://github.com/Osspial/winit.git", rev = "78a62ec5473e9cd5472c18f859103b0b0cb88362" }

[profile.dev]
opt-level = 0

[profile.dev.package.pico-args]
opt-level = 0

[profile.opt-dev]
inherits = "dev"
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
overflow-checks = true
debug-assertions = true
debug = true

[profile.profile]
inherits = "release"
debug = true
debug-assertions = false
lto = "thin"

[profile.lto]
inherits = "release"
debug = false
debug-assertions = false
lto = true
