cargo-features = ["named-profiles"]

[workspace]
members = [
    "bve",
    "bve-build",
    "bve-client",
    "bve-conveyor",
    "bve-corpus",
    "bve-derive",
    "bve-fuzz",
    "bve-native",
    "bve-obj-conv",
    "bve-render",
]

[patch.crates-io]
obj = { git = "https://github.com/kvark/obj.git", rev = "a1df2284ea11112aba5ee38b39b208344b634d7d" }

[profile.opt-dev]
inherits = "dev"
opt-level = 3
incremental = true
overflow-checks = true
debug-assertions = true
debug = true

[profile.release]
debug = false
debug-assertions = false
lto = true

[profile.profile]
inherits = "release"
debug = true
debug-assertions = false
lto = true
