[workspace]
members = ["bve*"]
exclude = ["bve-reborn"]    # Ignore the Unity project cause it's not a Rust project

[patch.crates-io]
cgmath = { git = "https://github.com/rustgd/cgmath.git", branch = "master" }

[profile.release]
overflow-checks = true
debug-assertions = true
