[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "WTFPL",
]

[bans]
multiple-versions = "deny"
skip = [
    # cocoa (winit has old version)
    { name = "cocoa", version = "0.19.1" },
    { name = "core-foundation", version = "0.6.4" },
    { name = "core-foundation-sys", version = "0.6.2" },
    { name = "core-graphics", version = "0.17.3" },
    # Winit
    { name = "rusttype", version = "0.7.9" }, # smithay-clinet-toolkit requires this; shell around 0.8.2, not really worrying
    { name = "winapi", version = "0.2.8" }, # smithay-clinet-toolkit requires this
    { name = "quote", version = "0.6.13" }, # wayland-client requires this
    { name = "proc-macro2", version = "0.4.30" }, # wayland-client requires this
    { name = "unicode-xid", version = "0.1.0" }, # wayland-client requires this
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
