[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "WTFPL",
]

[bans]
multiple-versions = "deny"
skip = [
    # Winit
    { name = "rusttype", version = "0.7.9" }, # smithay-clinet-toolkit requires this; shell around 0.8.2, not really worrying
    { name = "winapi", version = "0.2.8" }, # smithay-clinet-toolkit requires this
    { name = "quote", version = "0.6.13" }, # wayland-client requires this
    { name = "proc-macro2", version = "0.4.30" }, # wayland-client requires this
    { name = "unicode-xid", version = "0.1.0" }, # wayland-client requires this
    # graphics
    { name = "libloading", version = "0.5.2" }, # graphics stack uses old verison
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
    "RUSTSEC-2019-0031", # spin is unmaintained, need to pester flume to remove it
    "RUSTSEC-2020-0016"  # async-std is using net2 which id deprecated in favor of socket2
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
