[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "WTFPL",
    "Zlib",
]

[bans]
multiple-versions = "deny"
