[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
]

[bans]
multiple-versions = "deny"
skip = [
    # Winit
    { name = "winapi", version = "0.2.8" }, # winit -> mio-extras -> mio requires this
    # graphics
    { name = "libloading", version = "0.5.2" }, # graphics stack uses old verison
    { name = "miniz_oxide", version = "0.3.7" }, # png uses old version
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
    "RUSTSEC-2019-0031", # spin is unmaintained, need to pester flume to remove it
    "RUSTSEC-2020-0016"  # async-std is using net2 which id deprecated in favor of socket2
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
