[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "WTFPL",

]

[bans]
multiple-versions = "deny"
skip = [
    { name = "version_check", version = "0.1.5" }, # Dependency of nom 4
    { name = "nom", version = "4" }, # cexpr is quite old and looking unmaintained
    { name = "strsim", version = "0.8.0" }, # clap 2 isn't in dev anymore, change merged with clap 3.
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
