name: build
on: [push, pull_request]

env:
  RUST_BACKTRACE: full

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2020-03-19]
        os: [windows-2019, macos-latest, ubuntu-18.04]
        include:
          - rust: nightly-2020-03-19
            triple: x86_64-pc-windows-msvc
            os: windows-2019
            name: windows-build

          - rust: nightly-2020-03-19
            triple: x86_64-apple-darwin
            os: macos-latest
            name: mac-build

          - rust: nightly-2020-03-19
            triple: x86_64-unknown-linux-gnu
            os: ubuntu-18.04
            name: linux-build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set Env (win)
        run: |
          echo "::add-path::$env:USERPROFILE\.cargo\bin"
        shell: powershell
        if: matrix.os == 'windows-2019'

      - name: Set Env (nix)
        run: |
          echo "::add-path::$HOME/.cargo/bin"
        shell: bash
        if: matrix.os != 'windows-2019'

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ matrix.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-index-

      - name: Cache build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.os }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-build-

      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none --profile minimal -y
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-2019'
        shell: bash

      - name: Update Rustup
        run: |
          rustup self update
          rustup set profile minimal
        shell: bash

      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup set default-host ${{ matrix.triple }}
          rustup toolchain install ${{ matrix.rust }}
        shell: bash

      - name: Build
        run: |
          cargo build --all
          cargo run --bin bve-build -- --color=always --bindgen
        shell: bash

      - name: Run tests
        run: |
          cargo test --all
        shell: bash

      - name: Docs
        run: |
          cargo doc --all --no-deps
        shell: bash

      - name: CMake on C API
        run: |
          mkdir -p target/capi/debug/
          cd target/capi/debug/
          cmake ../../../bve-native/tests/
          cmake --build .
          cd -
        shell: bash

      - name: Run C API (win)
        run: |
          target/capi/debug/Debug/bve-native-c.exe
          target/capi/debug/Debug/bve-native-c.exe
        shell: bash
        if: matrix.os == 'windows-2019'

      - name: Run C API (unix)
        run: |
          target/capi/debug/bve-native-c
          target/capi/debug/bve-native-cpp
        shell: bash
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-18.04'
