name: build
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        rust: [1.40.0]
        os: [windows-2019, macOS-10.15, ubuntu-18.04]
        include:
          - rust: 1.40.0
            os: windows-2019
            name: windows-1.40.0

          - rust: 1.40.0
            os: macOS-10.15
            name: mac-1.40.0

          - rust: 1.40.0
            os: ubuntu-18.04
            name: linux-1.40.0
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none --profile minimal -y
        if: matrix.os == 'macOS-10.15' || matrix.os == 'windows-2019'
        shell: bash

      - name: Update Rustup
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          rustup self update
          rustup set profile minimal
        shell: bash

      - name: Install Rust ${{ matrix.rust }}
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          rustup toolchain install ${{ matrix.rust }}
        shell: bash

      - uses: actions/checkout@v1

      - name: Build
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo build --all --tests
        shell: bash

      - name: Run tests
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo test --all
        shell: bash
