name: pr
on: [pull_request]

jobs:
  build:
    name: ${{ matrix.tool }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2019-10-15]
        tool: [clippy, rustfmt, audit]
    runs-on: ubuntu-18.04

    steps:
      - name: Update Rustup
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          rustup self update
          rustup set profile minimal
        shell: bash

      - name: Install Rust ${{ matrix.rust }}
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          rustup toolchain install ${{ matrix.rust }}
        shell: bash

      - name: Install Clippy
        if: matrix.tool == 'clippy'
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          rustup component add clippy --toolchain ${{ matrix.rust }}
        shell: bash

      - name: Install Rustfmt
        if: matrix.tool == 'rustfmt'
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          rustup component add rustfmt --toolchain ${{ matrix.rust }}
        shell: bash

      - name: Install Cargo Audit
        if: matrix.tool == 'audit'
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo install cargo-audit
        shell: bash

      - uses: actions/checkout@v1

      - name: Run Clippy
        if: matrix.tool == 'clippy'
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo clippy --all --tests -- -D warnings
        shell: bash

      - name: Run Rustfmt
        if: matrix.tool == 'rustfmt'
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo fmt --all -- --check
        shell: bash

      - name: Run Cargo Audit
        if: matrix.tool == 'audit'
        run: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo audit
        shell: bash