name: release
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
      - 'build*'

env:
  RUST_BACKTRACE: full

jobs:
  release:
    name: ${{ matrix.job-name }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2020-03-19]
        os: [windows-2019, macos-latest, ubuntu-18.04]
        include:
          - rust: nightly-2020-03-19
            triple: x86_64-pc-windows-msvc
            os: windows-2019
            job-name: windows-release
            name: windows
            suffix: .exe

          - rust: nightly-2020-03-19
            triple: x86_64-apple-darwin
            os: macos-latest
            job-name: macos-release
            name: mac
            suffix:

          - rust: nightly-2020-03-19
            triple: x86_64-unknown-linux-gnu
            os: ubuntu-18.04
            job-name: linux-release
            name: linux
            suffix:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set Env (win)
        run: |
          echo "::add-path::$env:USERPROFILE\.cargo\bin"
        shell: powershell
        if: matrix.os == 'windows-2019'

      - name: Set Env (nix)
        run: |
          echo "::add-path::$HOME/.cargo/bin"
        shell: bash
        if: matrix.os != 'windows-2019'

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none --profile minimal -y
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-2019'
        shell: bash

      - name: Update Rustup
        run: |
          rustup self update
          rustup set profile minimal
        shell: bash

      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup set default-host ${{ matrix.triple }}
          rustup toolchain install ${{ matrix.rust }}
        shell: bash

      - name: Install GLSLC (win)
        run: |
          curl https://ci.bvereborn.com/glslc-win.7z -o $env:USERPROFILE\glslc-win.7z
          7z x $env:USERPROFILE\glslc-win.7z -o"$env:USERPROFILE"
          ls $HOME
          echo "::add-path::$env:USERPROFILE"
        shell: powershell
        if: matrix.os == 'windows-2019'

      - name: Install GLSLC (mac)
        run: |
          curl https://ci.bvereborn.com/glslc-mac.tar.xz -o $HOME/glslc-mac.tar.xz
          tar -xf $HOME/glslc-mac.tar.xz -C $HOME
          ls $HOME
          echo "::add-path::$HOME"
        shell: bash
        if: matrix.os == 'macos-latest'

      - name: Install GLSLC (linux)
        run: |
          curl https://ci.bvereborn.com/glslc-linux.7z -o $HOME/glslc-linux.7z
          7z x $HOME/glslc-linux.7z -o$HOME
          chmod +x $HOME/glslc
          ls -lah $HOME
          echo "::add-path::$HOME"
        shell: bash
        if: matrix.os == 'ubuntu-18.04'

      - name: Build Shaders
        run: |
          cargo run --package bve-build -- --shaderc
        shell: bash

      - name: Build
        run: |
          cargo build -Z unstable-options --profile lto -p bve-client -p bve-corpus -p bve-obj-conv
        shell: bash

      - name: Build
        run: |
          mkdir ${{ matrix.name }}
          cp -r target/lto/bve-client${{ matrix.suffix }} target/lto/bve-corpus${{ matrix.suffix }} target/lto/bve-parser-run${{ matrix.suffix }} target/lto/bve-obj-conv${{ matrix.suffix }} bve-render/shaders/spirv ${{ matrix.name }}
        shell: bash

      - uses: actions/upload-artifact@v1
        with:
          name: bve-${{ matrix.name }}
          path: ${{ matrix.name }}
