name: repo-state
on: 
  pull_request:
  push:
    branches:
      - master
      - 'update-**'
      - 'ci-**'

env:
  RUST_BACKTRACE: full

jobs:
  build:
    name: ${{ matrix.tool }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2020-02-05]
        tool: [clippy, rustfmt, deny]
    container: cwfitzgerald/bve-dev-env:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Run Clippy
        if: matrix.tool == 'clippy'
        run: |
          cargo "+${{ matrix.rust }}" clippy --all --tests -- -D warnings
        shell: bash

      - name: Run Rustfmt
        if: matrix.tool == 'rustfmt'
        run: |
          cargo "+${{ matrix.rust }}" fmt --all -- --check
        shell: bash

      - name: Run Cargo Deny
        if: matrix.tool == 'deny'
        run: |
          cargo "+${{ matrix.rust }}" deny check
        shell: bash
