name: repo-state
on: 
  pull_request:
  push:
    branches:
      - master
      - 'update/**'

jobs:
  build:
    name: ${{ matrix.tool }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2020-02-05]
        tool: [clippy, rustfmt, deny]
    runs-on: ubuntu-18.04

    steps:
      - name: Set Env (nix)
        run: echo "::add-path::$HOME/.cargo/bin"
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: repostate-${{ matrix.tool }}-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: repostate-${{ matrix.tool }}-cargo-index

      - name: Cache Binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: repostate-${{ matrix.tool }}-binary

      - name: Cache AdvisoryDB
        uses: actions/cache@v1
        env:
          cache-name: advisorydb
        with:
          env:
            cache-name: advisorydb
          path: ~/.cargo/bin
          key: repostate-${{ matrix.tool }}-advisorydb
        if: matrix.tool == deny

      - name: Update Rustup
        run: |
          rustup self update
          rustup set profile minimal
        shell: bash

      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup toolchain install ${{ matrix.rust }}
        shell: bash

      - name: Install Clippy
        if: matrix.tool == 'clippy'
        run: |
          rustup component add clippy --toolchain ${{ matrix.rust }}
        shell: bash

      - name: Install Rustfmt
        if: matrix.tool == 'rustfmt'
        run: |
          rustup component add rustfmt --toolchain ${{ matrix.rust }}
        shell: bash

      - name: Install Cargo Deny
        if: matrix.tool == 'deny'
        run: |
          cargo "+${{ matrix.rust }}" install cargo-deny
        shell: bash

      - name: Run Clippy
        if: matrix.tool == 'clippy'
        run: |
          cargo "+${{ matrix.rust }}" clippy --all --tests -- -D warnings
        shell: bash

      - name: Run Rustfmt
        if: matrix.tool == 'rustfmt'
        run: |
          cargo "+${{ matrix.rust }}" fmt --all -- --check
        shell: bash

      - name: Run Cargo Deny
        if: matrix.tool == 'deny'
        run: |
          cargo "+${{ matrix.rust }}" deny check
        shell: bash
